version: '3.8'
services:
  app:
    build:
      context: ../src
      dockerfile: ./dockerfile
    ports:
      - 9000:80
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
    container_name: app

  loki:
    image: "grafana/loki:latest"
    hostname: logs
    volumes:
      - loki:/loki
    ports:
      - "3100:3100" # http and Grafana data source

  grafana:
    image: grafana/grafana-oss:latest-ubuntu
    hostname: grafana
    ports: 
      - "3000:3000" #UI
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki

networks:
  mynetwork:

volumes:
  grafana: ~
  loki: ~
