global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
        
  - job_name: 'app'
    static_configs:
      - targets: [ 'app:9000' ]
